### ISSUE TITLE
setup.json for running setup

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/automation-lib#65]
At the moment, running a setup requires a setup.json file with all information regarding the environment to build.
In order to facilitate automation of building several different environments, code to build this setup.json from scratch can be useful

**Comment by wimpers** [comment]
@simonOpenV what does this exactly do? What is the required input? Can you elaborate a bit more in the ticket or document this.

**Comment by sjovdnbos** [comment]
This will introduce code for automatic generation of a setup file for clusters, i.e. code still need to be written in order to end up with a json file, but this is a first step towards simplified generation of a setup.json file for larger clusters (which can then be generated by a GUI for example, but this is not the scope of this ticket).

**Comment by wimpers** [comment]
Note to self: 

Code to implement the required functions in the backend to create a json through API/GUI f.e.
* add/remove domains to json
* add/remove roles from SR
* add remove SRs
* add backends, , presets, claim disks
* ...

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/automation-lib/releases/tag/0.5.0
Packaged in openvstorage-automation-lib_0.5.0-1_amd64.deb
