### ISSUE TITLE
Support some extra features on the setup.json

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/automation-lib#72]
The automation-lib, setup-runner doesn't allow us to configure the mds_safety of a vpool, change the quota levels of the caches and adding roles to an already existing partition.

- support mds_safety on the setup.json
- support quota levels (fragment cache, block cache) on the setup.json
- allow adding roles to an already existing partition (external arakoons mountpoint)

**Comment by jeroenmaelbrancke** [comment]
https://github.com/openvstorage/setup-runner/issues/9

**Comment by JeffreyDevloo** [comment]
Introduced in https://github.com/openvstorage/automation-lib/releases/tag/0.4.1
