### ISSUE TITLE
automation lib depends on integration tests

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/automation-lib#77]
Due to faulty inheritance between the automation lib and the integration tests, the automation lib was not standalone anymore. 
This is due to retrieving a settings.json file in the automation lib, which should only be present  in the  integration test environment

**Comment by sjovdnbos** [comment]
Fixed in https://github.com/openvstorage/automation-lib/pull/76 openvstorage-automation-lib-0.5.0-dev.1517924579.68e6541
https://github.com/openvstorage/integrationtests/pull/611 openvstorage-test-3.4.1-dev.1517924660.af34bf2

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/automation-lib/releases/tag/0.5.0
Packaged in openvstorage-automation-lib_0.5.0-1_amd64.deb
